<?php

/**
 * Implements hook_theme() to add the template definition.
 **/
function stepper_angular_app_page_attachments(array &$page) {
    $base = [
        '#type' => 'html_tag',
        '#tag' => 'base',
        '#attributes' => array(
            'href' => 'http://159.89.1.212/stepper-angular',
        ),
    ];

    $page['#attached']['html_head'][] = [$base, 'base'];
}
function stepper_angular_app_theme($existing, $type, $theme, $path) {

    return [
        'angular-calendar' => [
        ],
    ];
}
