name: 'Config Actions'
type: module
description: 'Enables modules to provide actions that modify configuration.'
# core: 8.x

# Information added by Drupal.org packaging script on 2018-03-19
version: '8.x-1.0-beta4'
core: '8.x'
project: 'config_actions'
datestamp: 1521499687
